Add reviews
brawo1994/java-filmorate pull request #10
Opened 2022-12-23 18:49 UTC by KokotAlex

2022-12-23 21:42 UTC, TatianaAV approved these changes

2022-12-23 23:24 UTC, heydancer requested changes

2022-12-23 23:24 UTC, heydancer commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +import org.springframework.web.bind.annotation.*;
Использование формы с применением символа звездочки может привести к увеличению времени компиляции — особенно при импорте нескольких больших пакетов. Поэтому лучше явно указывать имена классов

2022-12-23 23:24 UTC, heydancer commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/impl/ReviewDbStorage.java
> +import java.util.*;
лучше явно указывать имена классов

2022-12-24 11:43 UTC, brawo1994 commented on src/main/resources/schema.sql
> +    is_Positive     BOOLEAN
Думаю для однообразности нужно с маленькой буквы после подчеркивания, snake_case же)

2022-12-24 13:49 UTC, TatianaAV approved these changes

2022-12-24 13:52 UTC, TatianaAV commented on src/main/resources/schema.sql
> +    is_Positive     BOOLEAN
это sql там либо заглавные, либо строчные через подчеркивание

2022-12-25 07:50 UTC, KokotAlex commented on src/main/resources/schema.sql
> +    is_Positive     BOOLEAN
исправлено

2022-12-25 08:02 UTC, TatianaAV approved these changes

2022-12-25 11:41 UTC, brawo1994 approved these changes

2022-12-25 16:28 UTC, merged