Develop
brawo1994/java-filmorate pull request #16
Opened 2022-12-26 14:30 UTC by brawo1994

2022-12-26 19:55 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-12-26 19:55 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getPopularFilms(
В новом функционале `List` в старом интерфейс `Collection`.
Помните что важна консистентность и единообразие!

А List конечно же более общеупотребителен, используйте его...

2022-12-26 19:55 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        return reviewService.addReviewGrade(reviewId, userId, 1);
С точки зрения API на уровне класса предпочтительнее выставить два метода, ну например с названиями
like(reviewId, userId)
dislike(reviewId, userId)
Там внутри вертитесь как хотите приводите к одному методу с +1 и -1.
А наружу выставляем два понятных метода, в которые нельзя случайно взять и передать +100 и -100 ! ))

2022-12-26 19:55 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +    name            VARCHAR(255)    NOT NULL
Как то у вас почти все строки по 255 !
Ну как так что и name и description одинаковы!
Плохо продумали модель? А это ведь важно! Ну не поместиться в 255 символов никакое описание! Сразу прилетит запрос на увеличения поля... от недовольных клиентов! )))

```
    name            VARCHAR(255)    NOT NULL,
    description     VARCHAR(255)    NOT NULL,
```

2022-12-26 19:55 UTC, FanaticFiz commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:db/filmorate
Обычно я топлю за то чтобы вы сразу привыкали к написанию файла свойств для приложения в формате `yaml -> application.yml`

Попробуйте, может и вам понравится! 
Это чисто практический совет, не встречаю уже давно проектов с application.properties

2022-12-26 19:55 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public Collection<EventHistory> getEHistoryByUserId(@PathVariable int id) {
Соответственно по всему проекту Collection -> List

2022-12-26 19:55 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private int reviewId;
Делайте отступы между полями, когда много аннотаций, всё сливается!

2022-12-26 19:55 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    public void checkDirectorExist(int id) {
Если планируете кидаться ексепшеном, то назовите метод соответствующе: `throwIfNotExist`

2022-12-26 19:55 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorStorage.java
> +    Director getById(int id);
При одиночной выборке объектов уместно и очень удобно использовать `Optional`

2022-12-26 19:55 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/impl/DirectorDbStorage.java
> +            throw new NotExistException("Director with id: " + id + " does not exist");
Из хранилища/dao нельзя кидаться такими ексепшенами... Это работа сервиса!
Сервис обращается к хранилищу и потом делает выводы. 
Именно поэтому у вас "худые" сервисы!

2022-12-26 19:55 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>          return filmStorage.getFilms();
Во первых давайте использовать глагол `get` в сервисах, а `find` в хранилищах.

2022-12-26 19:55 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>          return filmStorage.getFilms();
Но тут еще вот что!

Присутствует проблема N+1
Поясню...
пусть у нас есть 100 фильмов... а у каждого из них есть жанры
для того чтобы собрать всё в одно и отдать при запросе нам нужно:
- достать все фильмы
- и все жанры к ним

Если делать "в лоб" то приходиться к каждому из 100-а фильмов отдельным запросом доставать еще и жанры...

получается ОДИН запрос на получение всех 100 фильмов и еще 100 запросов чтобы к каждому фильму подтянуть жанры....

Это называется проблема `N+1`
Чтобы её избежать мы должны заморочиться и в итоге приходим к всего ДВУМ запросам, вместо 101 !
Первый запрос на все фильмы, второй на все жанры для этих фильмов.

И делаем мы это в сервисе фильмов...

2022-12-26 19:55 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaService.java
>          return mpaStorage.getById(id);
Вот примените тут Optional(ну т.е. чтобы хранилище возвращало Optional<Mpa> ) и его метод orElseThrow и избавитесь от метода `checkMpaExist`

2022-12-27 06:41 UTC, KokotAlex commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        return reviewService.addReviewGrade(reviewId, userId, 1);
Исправлено

2022-12-27 06:53 UTC, KokotAlex commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:db/filmorate
Исправлено

2022-12-28 06:35 UTC, TatianaAV commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>          return filmStorage.getFilms();
N+1 исправлено. Осталось перенести в сервис.

2022-12-28 07:15 UTC, brawo1994 commented on src/main/resources/schema.sql
> +    name            VARCHAR(255)    NOT NULL
Поправил

2022-12-28 07:15 UTC, brawo1994 commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    public void checkDirectorExist(int id) {
В работе

2022-12-28 07:15 UTC, brawo1994 commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/impl/DirectorDbStorage.java
> +            throw new NotExistException("Director with id: " + id + " does not exist");
В работе

2022-12-28 19:51 UTC, FanaticFiz approved these changes

2022-12-29 03:35 UTC, KokotAlex approved these changes

2022-12-29 03:36 UTC, merged